// client/src/renderer/Sidebar.tsx
import { Link } from 'react-router-dom';

export default function Sidebar() {
  return (
    <div className="sidebar">
      Sidebar
      <nav>
        <ul>
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <Link to="/rooms">Rooms</Link>
          </li>
          <li>
            <Link to="/butts">Butts</Link>
          </li>
        </ul>
      </nav>
    </div>
  );
}

// client/src/components/Sidebar.vue
<script setup lang="ts"></script>

<template>
  <nav class="sidebar">
    <ul>
      <li>
        <router-link to="/">Home</router-link>
      </li>
      <li>
        <router-link to="/characters">Characters</router-link>
      </li>
      <li>
        <router-link to="/rooms">Rooms</router-link>
      </li>
    </ul>
  </nav>
</template>

<style scoped></style>
